fix: add importlib-metadata<5.0.0
Due to new importlib-metadata release:

    https://importlib-metadata.readthedocs.io/en/latest/history.html#v5-0-0

The test execution gives the following error on Python 3.7:

    AttributeError: 'EntryPoints' object has no attribute 'get'